name: "Snyk Container Test For My Mortal Kombat App"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'MK Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
    # Docker Build
    - name: Build Container     
      run: |
         docker build .  -t jkeely/my-mkjs-app:best
    # Run Snyk Container     
    - name: Run Snyk Container
      run: |
         snyk container test --file=Dockerfile jkeely/my-mkjs-app:best  --severity-threshold=high
         snyk container monitor jkeely/my-mkjs-app:best
      continue-on-error: true  
             
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jkeely/my-mkjs-app:best