name: "Snyk Code Test"
# Created a Github Action to execute on a "push" to the Master Branch. This will trigger a "snyk code test"
# against my application.  The output will be in html format and uploads it as an artifact.

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Test against MK'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}

    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         snyk code test  
      continue-on-error: true